# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0003_auto_20171127_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image4',
            new_name='image_4',
        ),
    ]
