# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0010_auto_20171130_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colorfield',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
