# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0011_auto_20171130_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfield',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='colorfield',
            name='is_main',
        ),
        migrations.AddField(
            model_name='colorfield',
            name='col_all',
            field=models.CharField(default=1, max_length=64, verbose_name=''),
            preserve_default=False,
        ),
    ]
