# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0014_auto_20171130_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorfield',
            name='name',
            field=models.BooleanField(default=1, max_length=16, verbose_name='\u0435\u0441\u043b\u0438 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'),
            preserve_default=False,
        ),
    ]
