# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0015_colorfield_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfield',
            name='name',
        ),
    ]
