# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0017_auto_20171130_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorfield',
            name='color_primer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.Product'),
        ),
        migrations.AlterField(
            model_name='colorfield',
            name='name',
            field=models.CharField(max_length=16, verbose_name='\u0435\u0441\u043b\u0438 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'),
        ),
    ]
