# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0018_auto_20171130_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorfield',
            old_name='color_primer',
            new_name='product',
        ),
    ]
