# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0019_auto_20171130_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfield',
            name='name',
        ),
        migrations.AlterField(
            model_name='colorfield',
            name='color_img',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='products_images/', verbose_name='\u0446\u0432\u0435\u0442 \u0442\u043e\u0432\u0430\u0440\u0430 (\u0444\u043e\u0442\u043e)'),
        ),
        migrations.AlterField(
            model_name='colorfield',
            name='name_color',
            field=models.CharField(default='\u0411\u0435\u043b\u044b\u0439', max_length=16, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0446\u0432\u0435\u0442\u0430'),
        ),
    ]
