# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0020_auto_20171130_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorfield',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.Product'),
        ),
    ]
