# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0021_auto_20171130_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorfield',
            old_name='name_color',
            new_name='name',
        ),
    ]
