# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0024_issuesprodukt'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesprodukt',
            name='issues_url',
            field=models.URLField(default=1, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0441 \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u043f\u0440\u0438\u0448\u0435\u043b \u0432\u043e\u043f\u0440\u043e\u0441'),
            preserve_default=False,
        ),
    ]
