# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suvenirka_product', '0026_auto_20180116_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesprodukt',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
