# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0028_remove_issuesprodukt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442 \u0432 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u044b \u0432 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f\u0445 \u0442\u043e\u0432\u0430\u0440\u0430',
            },
        ),
    ]
