# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0032_auto_20180307_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='description_category',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.ProductCategory'),
        ),
    ]
