# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 footer :1')),
                ('text2', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 footer :2')),
                ('text3', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 footer :3')),
                ('text4', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 footer :4')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441 \u0434\u043b\u044f footer ',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441 \u0434\u043b\u044f footer',
            },
        ),
        migrations.CreateModel(
            name='Home_and_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('stati_title', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('stati_text', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438')),
                ('short_name2', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :2')),
                ('stati_title2', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :2')),
                ('stati_text2', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :2')),
                ('short_name3', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :3')),
                ('stati_title3', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :3')),
                ('stati_text3', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :3')),
                ('short_name4', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u04354')),
                ('stati_title4', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u04384')),
                ('stati_text4', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u04384')),
                ('short_name5', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :5')),
                ('stati_title5', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :5')),
                ('stati_text5', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :5')),
                ('short_name6', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u04356')),
                ('stati_title6', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u04386')),
                ('stati_text6', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u04386')),
                ('short_name7', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :7')),
                ('stati_title7', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :7')),
                ('stati_text7', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :7')),
                ('short_name8', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :8')),
                ('stati_title8', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :8')),
                ('stati_text8', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :8')),
                ('short_name9', models.CharField(max_length=30, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 :9')),
                ('stati_title9', models.CharField(blank=True, max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0430\u0442\u044c\u0438 :9')),
                ('stati_text9', models.TextField(blank=True, verbose_name='\u0422\u0435\u043b\u043e \u0421\u0442\u0430\u0442\u044c\u0438 :9')),
            ],
            options={
                'verbose_name': '\u0421\u0422\u0410\u0422\u042c\u042f',
                'verbose_name_plural': '\u0421\u0422\u0410\u0422\u042c\u0418',
            },
        ),
        migrations.CreateModel(
            name='Title_pape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_on_pape', models.CharField(blank=True, max_length=80, verbose_name='TITLE \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('description_on_pape', models.CharField(blank=True, max_length=200, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('keywords_on_pape', models.CharField(blank=True, max_length=150, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('yandex_key', models.CharField(blank=True, max_length=250, verbose_name='\u043a\u043b\u044e\u0447 \u044f\u043d\u0434\u0435\u043a\u0441\u0430')),
                ('google_key', models.CharField(blank=True, max_length=250, verbose_name='\u043a\u043b\u044e\u0447 google ')),
                ('snipet', models.TextField(blank=True, max_length=500, verbose_name='\u041c\u043e\u0436\u043d\u043e \u043f\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0441\u0432\u043e\u0439 \u0441\u043d\u0438\u043f\u0435\u0442 cod')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updates', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TITLE + META',
                'verbose_name_plural': 'TITLE + META',
            },
        ),
        migrations.CreateModel(
            name='Top_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 TOP :1')),
                ('text2', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 TOP :2')),
                ('text3', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 TOP :3')),
                ('text4', models.CharField(blank=True, max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 TOP :4')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u0432\u0435\u0440\u0445\u043d\u0438\u0439 \u0447\u0430\u0441\u0442\u0438 ',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441 \u0434\u043b\u044f \u0432\u0435\u0440\u0445\u043d\u0438\u0439 \u0447\u0430\u0441\u0442\u0438',
            },
        ),
    ]
