# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
