# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0005_auto_20171123_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='\u041f\u043e\u0441\u0442\u0443\u043f\u0438\u043b', max_length=24),
        ),
    ]
