# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0006_auto_20171123_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Order'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
