# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0009_auto_20171126_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(default='\u041f\u043e\u0441\u0442\u0443\u043f\u0438\u043b \u043d\u043e\u0432\u044b\u0439 \u0437\u0430\u043a\u0430\u0437', max_length=24),
        ),
    ]
