# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0023_auto_20171130_1957'),
        ('suvenirka_order', '0012_auto_20171203_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='color_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.ColorField'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='order',
            field=models.ForeignKey(blank=True, default='\u041d\u043e\u0432\u044b\u0439', null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Order'),
        ),
    ]
