# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0015_auto_20171204_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='prod_color_name',
        ),
    ]
