# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0023_auto_20171130_1957'),
        ('suvenirka_order', '0016_remove_productinorder_prod_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='color_check',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.ColorField'),
        ),
    ]
