# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0018_auto_20171204_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='color_check',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
