# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0019_productinorder_color_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='color_check',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='color_check',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
