# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0020_auto_20171206_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_image',
            field=models.ImageField(default=1, upload_to='klient_images/'),
            preserve_default=False,
        ),
    ]
