# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0021_order_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_image',
            field=models.FileField(upload_to='klient_images/'),
        ),
    ]
