# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0022_auto_20171210_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoKlient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.FileField(upload_to='klient_images/')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e \u043a \u0437\u0430\u043a\u0430\u0437\u0443',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u043a \u0437\u0430\u043a\u0430\u0437\u0443',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.PhotoKlient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
