# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0024_auto_20171210_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Photoklient'),
        ),
    ]
