# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0029_auto_20171211_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userimages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
            preserve_default=False,
        ),
    ]
