# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0030_auto_20171215_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userimages',
        ),
    ]
