# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0032_auto_20171215_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='user_photo_in_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
            preserve_default=False,
        ),
    ]
