# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0033_auto_20171215_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='user_photo_in_order',
        ),
    ]
