# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0034_remove_productinorder_user_photo_in_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='user_photo_in_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
        ),
    ]
