# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0036_auto_20171215_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='image',
        ),
        migrations.AddField(
            model_name='userimage',
            name='id_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.ProductInOrder'),
        ),
    ]
