# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0037_auto_20171215_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='image',
            field=models.FileField(default=1, upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
