# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0038_auto_20171215_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='userimages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='image',
            field=models.FileField(default=1, upload_to='user_image/'),
            preserve_default=False,
        ),
    ]
