# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0039_auto_20171215_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userimages',
        ),
        migrations.AddField(
            model_name='userimage',
            name='ino',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Order'),
        ),
    ]
