# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0041_auto_20171215_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(upload_to='..user_image/'),
        ),
    ]
