# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0042_auto_20171219_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='us_photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
        ),
    ]
