# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0043_productinorder_us_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='us_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
            preserve_default=False,
        ),
    ]
