# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0044_auto_20171219_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='us_photo',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='image_url',
        ),
    ]
