# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0050_remove_order_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='us_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.ProductInOrder'),
        ),
    ]
