# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0052_auto_20171220_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='us_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
        ),
    ]
