# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0054_auto_20171220_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='us_image',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='image',
            field=models.FileField(blank=True, upload_to='..user_image/'),
        ),
    ]
