# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0055_auto_20171220_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='image',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='us_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
            preserve_default=False,
        ),
    ]
