# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0058_remove_productinorder_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='imonorder',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
