# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0063_auto_20171221_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='us_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Userimage'),
        ),
    ]
