# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0066_auto_20171222_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='imonorder',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='us_image',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='us_image',
            field=models.ManyToManyField(to='suvenirka_order.Userimage'),
        ),
    ]
