# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0068_auto_20171222_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(upload_to='..user_image/'),
        ),
    ]
