# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0069_auto_20171222_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437 \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410'},
        ),
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': '\u0422\u043e\u0432\u0430\u0440 \u0432 \u0437\u0430\u043a\u0430\u0437\u0435 \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b \u0432 \u0437\u0430\u043a\u0430\u0437\u0435 \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410'},
        ),
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': '\u0444\u043e\u0442\u043e \u043a \u0437\u0430\u043a\u0430\u0437\u0443 \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410', 'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u043a \u0437\u0430\u043a\u0430\u0437\u0443 \u0421\u0423\u0412\u0415\u041d\u0418\u0420\u041a\u0410'},
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.FileField(upload_to='user_image/'),
        ),
    ]
