# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suvenirka_order', '0070_auto_20171226_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
