# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0071_productinorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='user',
        ),
    ]
