# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0072_remove_productinorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Status'),
            preserve_default=False,
        ),
    ]
