# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0077_auto_20180211_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(max_length=24),
        ),
    ]
