# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_product', '0026_auto_20180116_0758'),
        ('suvenirka_order', '0080_auto_20180211_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='issues_produkt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_product.IssuesProdukt'),
        ),
    ]
