# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0082_auto_20180213_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='issues_produkt',
        ),
    ]
