# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='order__print_photo/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='NumberOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=6, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0417\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u041d\u043e\u043c\u0435\u0440 \u0417\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u041d\u043e\u043c\u0435\u0440\u0430 \u0417\u0430\u043a\u0430\u0437\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='OptionPhotoField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_photo', models.CharField(blank=True, default=None, max_length=3, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u043a\u043e\u043f\u0438\u0439')),
                ('with_margin', models.BooleanField(default=False, verbose_name='C \u043f\u043e\u043b\u044f\u043c\u0438 \u0438\u043b\u0438 \u0431\u0435\u0437')),
                ('time_take', models.CharField(choices=[('1', '\u041a\u0430\u043a \u043c\u043e\u0436\u043d\u043e \u0431\u044b\u0441\u0442\u0440\u0435\u0435'), ('2', '\u0412 \u0442\u0435\u0447\u0435\u043d\u0438\u0438 \u0434\u043d\u044f'), ('3', '\u041d\u0435 \u0441\u0440\u043e\u0447\u043d\u043e')], max_length=1, null=True, verbose_name='\u043a\u043e\u0433\u0434\u0430 \u0437\u0430\u0431\u0435\u0440\u0443\u0442')),
                ('comment', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), ('2', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('3', '\u0412\u044b\u0434\u0430\u043d')], max_length=1, null=True, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('number_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='just_print_photo.NumberOrder', verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0417\u0430\u043a\u0430\u0437\u0430')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_photo', to='just_print_photo.OptionPhotoField', verbose_name='\u041e\u043f\u0446\u0438\u0438 \u0437\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='PhotoProdukt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_photo', models.CharField(blank=True, default=None, max_length=10, verbose_name='\u0424\u043e\u0440\u043c\u0430\u0442 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('type_paper', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u0422\u0438\u043f \u0431\u0443\u043c\u0430\u0433\u0438')),
                ('price_smollshipment', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e 20\u0448\u0442')),
                ('price_medium_shipment', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442 20 \u0434\u043e 100\u0448\u0442')),
                ('price_big_shipment', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442 20 \u0434\u043e 100\u0448\u0442')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0440\u043c\u0430\u0442 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0438  \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b',
                'verbose_name_plural': '\u0424\u043e\u0440\u043c\u0430\u0442\u044b \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438 \u0438  \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='PrintPhotoHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='photo_doc/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432 \u0424\u043e\u0442\u043e \u043d\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
                'verbose_name_plural': '\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a\u0438 \u0432 \u0424\u043e\u0442\u043e \u043d\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='PrintPhotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='RespondentForPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('phone', models.CharField(max_length=25, verbose_name='\u0422\u0435\u043b. \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a\u0430')),
                ('namber_bank', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0447\u0435\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0420\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0420\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435',
            },
        ),
        migrations.CreateModel(
            name='StatusOrderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=35, verbose_name='C\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430',
                'db_table': 'photo_order',
                'managed': True,
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b \u0437\u0430\u043a\u0430\u0437\u0430',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u0418\u043c\u044f \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to='just_print_photo.User', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='optionphotofield',
            name='photo_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_product', to='just_print_photo.PhotoProdukt'),
        ),
    ]
