# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0002_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberorder',
            name='number_order',
            field=models.CharField(default='0', max_length=6, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0417\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
