# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0004_auto_20181016_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.CharField(default=None, max_length=100, verbose_name='\u0418\u043c\u044f \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
        ),
    ]
