# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0006_auto_20181016_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
