# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0007_auto_20181017_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionphotofield',
            name='with_margin',
            field=models.CharField(choices=[('1', '\u0421 \u043f\u043e\u043b\u044f\u043c\u0438'), ('2', '\u0411\u0435\u0437 \u043f\u043e\u043b\u0435\u0439'), ('3', '\u041d\u0430 \u0443\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0435')], max_length=1, null=True, verbose_name='C \u043f\u043e\u043b\u044f\u043c\u0438 \u0438\u043b\u0438 \u0431\u0435\u0437'),
        ),
    ]
