# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0008_auto_20181017_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionphotofield',
            options={'verbose_name': '\u043e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0439', 'verbose_name_plural': '\u043e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0439'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option',
        ),
        migrations.AddField(
            model_name='filephoto',
            name='options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OptionPhotoField', to='just_print_photo.OptionPhotoField', verbose_name='\u041e\u043f\u0446\u0438\u044f \u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionphotofield',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='just_print_photo.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionphotofield',
            name='count_photo',
            field=models.CharField(default=None, max_length=3, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u043a\u043e\u043f\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='optionphotofield',
            name='time_take',
            field=models.CharField(choices=[('0', '\u041a\u0430\u043a \u043c\u043e\u0436\u043d\u043e \u0431\u044b\u0441\u0442\u0440\u0435\u0435'), ('1', '\u0412 \u0442\u0435\u0447\u0435\u043d\u0438\u0438 \u0434\u043d\u044f'), ('2', '\u041d\u0435 \u0441\u0440\u043e\u0447\u043d\u043e')], max_length=1, null=True, verbose_name='\u043a\u043e\u0433\u0434\u0430 \u0437\u0430\u0431\u0435\u0440\u0443\u0442'),
        ),
        migrations.AlterField(
            model_name='optionphotofield',
            name='with_margin',
            field=models.CharField(choices=[('0', '\u0421 \u043f\u043e\u043b\u044f\u043c\u0438'), ('1', '\u0411\u0435\u0437 \u043f\u043e\u043b\u0435\u0439'), ('2', '\u041d\u0430 \u0443\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u0438\u0435')], max_length=1, null=True, verbose_name='C \u043f\u043e\u043b\u044f\u043c\u0438 \u0438\u043b\u0438 \u0431\u0435\u0437'),
        ),
    ]
