# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0010_optionphotofield_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionphotofield',
            name='file',
        ),
    ]
