# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0011_remove_optionphotofield_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='order__print_photo/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0424\u0430\u0439\u043b',
                'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b',
            },
        ),
        migrations.AlterField(
            model_name='filephoto',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='just_print_photo.Files', verbose_name='file'),
        ),
    ]
