# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0012_auto_20181022_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filephoto',
            name='file',
        ),
        migrations.AddField(
            model_name='optionphotofield',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='just_print_photo.Files', verbose_name='file'),
            preserve_default=False,
        ),
    ]
