# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0013_auto_20181022_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionphotofield',
            name='file',
        ),
        migrations.AddField(
            model_name='optionphotofield',
            name='files',
            field=models.FileField(blank=True, upload_to='order__print_photo/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
