# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0015_auto_20181022_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_f',
            field=models.CharField(default=1, max_length=6, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043a \u043f\u0435\u0447\u0430\u0442\u0438 \u0448\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='count_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043a \u043e\u043f\u043b\u0430\u0442\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='task_call',
            field=models.CharField(choices=[('0', '\u041d\u0415\u0422'), ('1', '\u0414\u0410')], default='0', max_length=1, verbose_name='\u041d\u0443\u0436\u0435\u043d \u0437\u0432\u043e\u043d\u043e\u043a \u043a\u043b\u0438\u0435\u043d\u0442\u0443'),
        ),
        migrations.AlterField(
            model_name='optionphotofield',
            name='time_take',
            field=models.CharField(choices=[('0', '\u041a\u0430\u043a \u043c\u043e\u0436\u043d\u043e \u0431\u044b\u0441\u0442\u0440\u0435\u0435'), ('1', '\u0412 \u0442\u0435\u0447\u0435\u043d\u0438\u0438 \u0434\u043d\u044f'), ('2', '\u041d\u0435 \u0441\u0440\u043e\u0447\u043d\u043e'), ('3', '\u0417\u0430\u0431\u0435\u0440\u0443 \u043f\u043e\u0441\u043b\u0435 \u0437\u0430\u0432\u0442\u0440\u0430'), ('4', '\u0417\u0430\u0431\u0435\u0440\u0443 \u043d\u0430 \u043d\u0435\u0434\u0435\u043b\u0438')], max_length=1, null=True, verbose_name='\u043a\u043e\u0433\u0434\u0430 \u0437\u0430\u0431\u0435\u0440\u0443\u0442'),
        ),
    ]
