# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0016_auto_20181022_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count_f',
        ),
    ]
