# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_print_photo', '0017_remove_order_count_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='\u0412\u0441\u0435\u0433\u043e \u043a \u043e\u043f\u043b\u0430\u0442\u0435'),
        ),
    ]
