# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='\u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0448\u0442. \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435.')),
            ],
            options={
                'verbose_name': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415',
                'verbose_name_plural': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415',
            },
        ),
        migrations.CreateModel(
            name='DocumentEditPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_edit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 \u0431\u0435\u0437 \u043f\u0435\u0447\u0430\u0442\u0438')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443',
            },
        ),
        migrations.CreateModel(
            name='DocumentFullPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e \u0431\u043b\u043e\u043a\u0430.')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e',
            },
        ),
        migrations.CreateModel(
            name='DocumentImagePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='photo_doc/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430',
                'verbose_name_plural': '\u043f\u0440\u0438\u043c\u0435\u0440\u044b \u0431\u043b\u043e\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='DocumentOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_document', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('count_photo', models.CharField(max_length=1, null=True, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435')),
                ('options_photo', models.CharField(max_length=1, null=True, verbose_name='\u043e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e')),
                ('full_price_photo', models.CharField(max_length=1, null=True, verbose_name='\u0446\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e\u0434')),
                ('edit_price_photo', models.CharField(max_length=1, null=True, verbose_name='\u0446\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443')),
                ('image_preview', models.CharField(max_length=1, null=True, verbose_name='\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='photo_doc/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0432 \u0424\u043e\u0442\u043e \u043d\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
                'verbose_name_plural': '\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a\u0438 \u0432 \u0424\u043e\u0442\u043e \u043d\u0430 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='PhotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
            },
        ),
    ]
