# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1, null=True, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, verbose_name='Email')),
                ('time', models.CharField(choices=[(1, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f \u0434\u043e 12:00'), (2, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  13:00'), (3, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  14:00'), (4, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  15:00'), (5, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  16:00'), (6, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  17:00'), (7, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  18:00'), (8, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  19:00'), (9, '\u0421\u0435\u0433\u043e\u0434\u043d\u044f  20:00'), (10, '\u0417\u0430\u0432\u0442\u0440\u0430 \u0434\u043e 12:00'), (11, '\u0417\u0430\u0432\u0442\u0440\u0430 \u043f\u043e\u0441\u043b\u0435 12:00')], max_length=1, null=True, verbose_name='\u043a\u043e\u0433\u0434\u0430 \u0437\u0430\u0431\u0435\u0440\u0435\u0442\u0435 \u0433\u043e\u0442\u043e\u0432\u043e\u0435')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('count_complect', models.CharField(blank=True, default=None, max_length=2, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u043e\u0432')),
                ('you_file', models.FileField(blank=True, null=True, upload_to='order_photo_of_doc/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437 \u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=35, verbose_name='C\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b \u0437\u0430\u043a\u0430\u0437\u0430',
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 \u0438 \u0435\u0433\u043e \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b', 'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b \u0438 \u0435\u0433\u043e \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='count_photo',
            field=models.CharField(choices=[(b'1', b'4'), (b'2', b'6')], max_length=1, null=True, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='image_preview',
            field=models.CharField(max_length=9999, null=True, verbose_name='\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430'),
        ),
    ]
