# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180918_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusorder',
            options={'managed': True, 'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b \u0437\u0430\u043a\u0430\u0437\u0430'},
        ),
        migrations.AlterModelTable(
            name='statusorder',
            table='photo_ordering_stat',
        ),
    ]
