# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180920_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoption',
            name='count_photo',
        ),
        migrations.RemoveField(
            model_name='documentoption',
            name='edit_price_photo',
        ),
        migrations.RemoveField(
            model_name='documentoption',
            name='full_price_photo',
        ),
        migrations.RemoveField(
            model_name='documentoption',
            name='image_preview',
        ),
        migrations.RemoveField(
            model_name='documentoption',
            name='options_photo',
        ),
        migrations.DeleteModel(
            name='DocumentOption',
        ),
    ]
