# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180920_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoptions',
            name='option',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='count_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentCount', verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='edit_price_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentEditPrice', verbose_name='\u0446\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='full_price_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentFullPrice', verbose_name='\u0446\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e\u0434'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='image_preview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentImagePreview', verbose_name='\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='options_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentOptions', verbose_name='\u043e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e'),
        ),
    ]
