# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20180920_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcount',
            options={'verbose_name': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415'},
        ),
        migrations.AlterModelOptions(
            name='documenteditprice',
            options={'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443'},
        ),
        migrations.AlterModelOptions(
            name='documentfullprice',
            options={'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e'},
        ),
        migrations.AlterModelOptions(
            name='documentimagepreview',
            options={'verbose_name': '\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u043f\u0440\u0438\u043c\u0435\u0440\u044b \u0431\u043b\u043e\u043a\u0430'},
        ),
        migrations.AlterModelOptions(
            name='documentoptions',
            options={'verbose_name': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e'},
        ),
    ]
