# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20180920_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcount',
            options={'verbose_name': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0448\u0442 \u0432 \u0411\u041b\u041e\u041a\u0415 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'},
        ),
        migrations.AlterModelOptions(
            name='documenteditprice',
            options={'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'},
        ),
        migrations.AlterModelOptions(
            name='documentfullprice',
            options={'verbose_name': '\u0426\u0435\u043d\u0430 \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u0426\u0435\u043d\u044b \u0437\u0430 \u0431\u043b\u043e\u043a c \u043f\u0435\u0447\u0430\u0442\u044c\u044e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'},
        ),
        migrations.AlterModelOptions(
            name='documentimagepreview',
            options={'verbose_name': '\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u043f\u0440\u0438\u043c\u0435\u0440\u044b \u0431\u043b\u043e\u043a\u0430 (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'},
        ),
        migrations.AlterModelOptions(
            name='documentoptions',
            options={'verbose_name': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)', 'verbose_name_plural': '\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e (\u043d\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e)'},
        ),
        migrations.AlterField(
            model_name='documentcount',
            name='count',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True, verbose_name='\u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0448\u0442. \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435.'),
        ),
        migrations.AlterField(
            model_name='documenteditprice',
            name='price_edit',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 \u0431\u0435\u0437 \u043f\u0435\u0447\u0430\u0442\u0438'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentfullprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e \u0431\u043b\u043e\u043a\u0430.'),
        ),
        migrations.AlterField(
            model_name='documentimagepreview',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='photo_doc/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='documentoptions',
            name='option',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='\u041e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='count_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentCount', verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0444\u043e\u0442\u043e \u0432 \u0431\u043b\u043e\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='edit_price_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentEditPrice', verbose_name='\u0446\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='full_price_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentFullPrice', verbose_name='\u0446\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e\u0434'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='image_preview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentImagePreview', verbose_name='\u043f\u0440\u0438\u043c\u0435\u0440 \u0431\u043b\u043e\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='options_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentOptions', verbose_name='\u043e\u043f\u0446\u0438\u0438 \u0444\u043e\u0442\u043e'),
        ),
    ]
