# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_auto_20180923_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteditprice',
            name='price_edit',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0443 \u0431\u0435\u0437 \u043f\u0435\u0447\u0430\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='documentimagepreview',
            name='image_preview',
            field=models.ImageField(upload_to='photo_doc/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435'),
        ),
    ]
