# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_auto_20180926_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderphoto',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='phone_number',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='you_file',
            field=models.FileField(blank=True, default=1, upload_to='order_photo_of_doc/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
            preserve_default=False,
        ),
    ]
