# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0011_auto_20180926_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('phone', models.CharField(max_length=25, verbose_name='\u0422\u0435\u043b. \u0421\u0431\u0435\u0440\u0431\u0430\u043d\u043a\u0430')),
                ('namber_bank', models.CharField(max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0441\u0447\u0435\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0420\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u0420\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0430 \u0432 \u0411\u0430\u043d\u043a\u0435',
            },
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='full_price_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.DocumentFullPrice', verbose_name='\u0446\u0435\u043d\u0430 \u0441 \u043f\u0435\u0447\u0430\u0442\u044c\u044e'),
        ),
        migrations.AlterField(
            model_name='orderphoto',
            name='status',
            field=models.CharField(choices=[('1', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), ('2', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('3', '\u0412\u044b\u0434\u0430\u043d')], max_length=1, null=True, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
