# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20180928_1004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPhoto',
        ),
    ]
