# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0013_delete_orderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), ('2', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d'), ('3', '\u0412\u044b\u0434\u0430\u043d')], max_length=1, null=True, verbose_name='\u0441\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('name_document', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430')),
                ('name_user', models.CharField(blank=True, default=None, max_length=100, verbose_name='\u0418\u043c\u044f \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
                ('email', models.EmailField(blank=True, default=None, max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('task', multiselectfield.db.fields.MultiSelectField(choices=[('1', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u0442\u044c \u0438 \u0432\u044b\u0441\u043b\u0430\u0442\u044c \u043d\u0430 \u043f\u043e\u0447\u0442\u0443'), ('2', '\u0420\u0430\u0441\u043f\u0435\u0447\u0430\u0442\u0430\u0442\u044c \u0431\u043b\u043e\u043a \u0444\u043e\u0442\u043e'), ('3', '\u0420\u0430\u0441\u043f\u0435\u0447\u0430\u0442\u0430\u0442\u044c \u0438 \u0432\u044b\u0441\u043b\u0430\u0442\u044c \u043d\u0430 \u043f\u043e\u0447\u0442\u0443')], max_length=3)),
                ('you_file', models.FileField(blank=True, upload_to='order_photo_of_doc/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('comment', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437 \u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0439',
            },
        ),
    ]
