# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider_up',
            name='slide_to_image',
        ),
        migrations.AddField(
            model_name='slider_image',
            name='image_to_slide',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider_up.Slider_up'),
        ),
    ]
