# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0002_auto_20171024_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_up',
            name='name_buttom',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='\u0442\u0435\u043a\u0441\u0442 \u0432 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='slider_up',
            name='slide_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435'),
        ),
    ]
