# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0003_auto_20171024_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='TITLE \u0434\u043b\u044f suvenirka.html')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description \u0434\u043b\u044f suvenirka.html')),
                ('keywords', models.CharField(blank=True, max_length=120, verbose_name='keywords \u0434\u043b\u044f suvenirka.html')),
            ],
            options={
                'verbose_name': 'SEO \u0434\u043b\u044f suvenirka/suvenirka.html',
            },
        ),
    ]
