# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0004_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='Description_suvenirka',
        ),
    ]
