# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0005_auto_20171222_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description_suvenirka',
            options={'verbose_name': 'SEO \u0434\u043b\u044f suvenirka/suvenirka.html', 'verbose_name_plural': 'SEO \u0434\u043b\u044f suvenirka/suvenirka.html'},
        ),
    ]
