# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0007_auto_20180312_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider_image',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435'},
        ),
        migrations.AlterModelOptions(
            name='slider_up',
            options={'verbose_name': '\u0422\u0435\u043a\u0441\u0442\u044b \u043a \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0443'},
        ),
        migrations.AddField(
            model_name='slider_image',
            name='image_mobile',
            field=models.ImageField(default=1, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043c\u043e\u0431'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 HD'),
        ),
    ]
