# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0008_auto_20180312_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_image',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 HD'),
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u043c\u043e\u0431'),
        ),
    ]
