# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0010_nameimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider_image',
            name='is_main',
        ),
        migrations.AddField(
            model_name='slider_image',
            name='image_pc',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 1360px'),
        ),
        migrations.AddField(
            model_name='slider_image',
            name='image_tablet',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 760px'),
        ),
        migrations.AlterField(
            model_name='slider_image',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 360px'),
        ),
    ]
