# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0012_auto_20180312_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider_image',
            name='image_mobile',
        ),
        migrations.RemoveField(
            model_name='slider_image',
            name='image_pc',
        ),
        migrations.RemoveField(
            model_name='slider_image',
            name='image_tablet',
        ),
    ]
