# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slider_up', '0013_auto_20180312_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_image_mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 HD')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_to_slide', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider_up.Slider_up')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435\u0440\u0443  360',
            },
        ),
        migrations.CreateModel(
            name='Slider_image_tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products_images/', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 HD')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_to_slide', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='slider_up.Slider_up')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435\u0440\u0443 768',
            },
        ),
        migrations.AlterModelOptions(
            name='slider_image',
            options={'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0432 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0435\u0440\u0443 1366'},
        ),
    ]
