# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refcartridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgePrinters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='\u0411\u0440\u0435\u043d\u0434')),
                ('model_printer', models.CharField(blank=True, default=None, max_length=50, verbose_name='\u041c\u043e\u0434\u0435\u043b\u0438 \u041f\u0440\u0438\u043d\u0442\u0435\u0440\u043e\u0432')),
                ('number_cartridge', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u041a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
                ('refill_cartridge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0417\u0430\u043f\u0440\u0430\u0432\u043a\u0430 \u043a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0430')),
                ('replacing_chip', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0417\u0430\u043c\u0435\u043d\u0430 \u0447\u0438\u043f\u0430')),
                ('replacing_printing_drum', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0417\u0430\u043c\u0435\u043d\u0430 \u0444\u043e\u0442\u043e\u0432\u0430\u043b\u0430')),
                ('replacing_magnetic', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='\u0417\u0430\u043c\u0435\u043d\u0430 \u041c\u0430\u0433\u043d\u0438\u0442\u043d\u043e\u0433\u043e \u0412\u0430\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0440\u0438\u0434\u0436 \u0438 \u043f\u0440\u0438\u043d\u0442\u0435\u0440',
                'db_table': 'CartridgeCase',
                'managed': True,
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u0440\u0438\u0434\u0436\u0438 \u0438 \u043f\u0440\u0438\u043d\u0442\u0435\u0440\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='cartridgesnumber',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='services',
            name='printe_or_cartridge',
        ),
        migrations.DeleteModel(
            name='CartridgesNumber',
        ),
        migrations.DeleteModel(
            name='PrinterModel',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
