# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_documents', '0003_auto_20181030_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiondocfield',
            old_name='count_photo',
            new_name='count_doc',
        ),
        migrations.RenameField(
            model_name='optiondocfield',
            old_name='photo_product',
            new_name='doc_product',
        ),
        migrations.AlterField(
            model_name='docprodukt',
            name='price_big_shipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442 20 \u0434\u043e 100\u0448\u0442'),
        ),
        migrations.AlterField(
            model_name='docprodukt',
            name='price_medium_shipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u043e\u0442 20 \u0434\u043e 100\u0448\u0442'),
        ),
        migrations.AlterField(
            model_name='docprodukt',
            name='price_smollshipment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043e 20\u0448\u0442'),
        ),
    ]
