# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 08:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('Petersburg', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
