# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180123_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_or_us_choise',
            field=models.CharField(choices=[('\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442', '\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442'), ('\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f', '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f')], default='\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442', max_length=2, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043a\u043b\u0438\u0435\u043d\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel_number',
            field=models.CharField(blank=True, max_length=24, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b'),
        ),
    ]
