# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180124_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel_number_two',
            field=models.CharField(blank=True, max_length=24, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_or_us_choise',
            field=models.CharField(choices=[('\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442', '\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442'), ('\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f', '\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f')], default='\u0427\u0430\u0441\u0442\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442', max_length=14, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043a\u043b\u0438\u0435\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
