# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvenirka_order', '0071_productinorder_user'),
        ('accounts', '0006_auto_20180124_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='suvenirka_order.ProductInOrder'),
            preserve_default=False,
        ),
    ]
